server {
    listen 80;
    server_name localhost;

    # 빌드된 React 파일들이 위치한 경로
    root /usr/share/nginx/html;
    index index.html;

    # React Router를 위한 설정:
    # 어떤 경로로 들어오든 실제 파일이 없다면 index.html을 서빙하여 React 내부 라우팅을 타게 함
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 오류 페이지 설정
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
